# This is a basic workflow to help you get started with Actions

name: Docker image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        uses: docker/login-action@v1.10.0
        with:
          # Username used to log against the Docker registry
          username: frostbitez
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKER_PASSWORD }}
          # Log out from the Docker registry at the end of a job
          logout: true
      
      - name: Maven build
        run: |
          mvn clean package -Dmaven.javadoc.skip=true -B -V

      - name: Docker building user service
        run: |
          cd user
          docker build -t "frostbitez/store-user:$GITHUB_SHA" .

      - name: Docker building stock service
        run: |
          cd stock
          docker build -t "frostbitez/store-stock:$GITHUB_SHA" .

      - name: Docker building product service
        run: |
          cd product
          docker build -t "frostbitez/store-product:$GITHUB_SHA" .

      - name: Docker building payment service
        run: |
          cd payment
          docker build -t "frostbitez/store-payment:$GITHUB_SHA" .

      - name: Docker building order service
        run: |
          cd order
          docker build -t "frostbitez/store-order:$GITHUB_SHA" .

      - name: Docker building delivery service
        run: |
          cd delivery
          docker build -t "frostbitez/store-delivery:$GITHUB_SHA" .

      - name: Docker building bag service
          run: |
            cd bag
            docker build -t "frostbitez/store-bag:$GITHUB_SHA" .